// <auto-generated />
using System;
using Desafio1MVCGrupoWASP.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Desafio1MVCGrupoWASP.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Desafio1MVCGrupoWASP.Models.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Departamentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Área de RRHH",
                            Nombre = "Recursos Humanos"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Área de TI",
                            Nombre = "Tecnología"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Área comercial",
                            Nombre = "Ventas"
                        });
                });

            modelBuilder.Entity("Desafio1MVCGrupoWASP.Models.Empleado", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("FechaContratacion")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Empleado");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DepartamentoId = 1,
                            FechaContratacion = new DateOnly(2010, 8, 15),
                            FechaNacimiento = new DateOnly(1985, 5, 20),
                            Nombre = "John Doe",
                            Salario = 50000m
                        },
                        new
                        {
                            ID = 2,
                            DepartamentoId = 2,
                            FechaContratacion = new DateOnly(2015, 1, 25),
                            FechaNacimiento = new DateOnly(1990, 3, 10),
                            Nombre = "Jane Smith",
                            Salario = 70000m
                        },
                        new
                        {
                            ID = 3,
                            DepartamentoId = 3,
                            FechaContratacion = new DateOnly(2012, 6, 18),
                            FechaNacimiento = new DateOnly(1982, 11, 22),
                            Nombre = "Mark Johnson",
                            Salario = 55000m
                        },
                        new
                        {
                            ID = 4,
                            DepartamentoId = 1,
                            FechaContratacion = new DateOnly(2005, 10, 12),
                            FechaNacimiento = new DateOnly(1978, 7, 30),
                            Nombre = "Emily Davis",
                            Salario = 75000m
                        },
                        new
                        {
                            ID = 5,
                            DepartamentoId = 2,
                            FechaContratacion = new DateOnly(2020, 4, 15),
                            FechaNacimiento = new DateOnly(1995, 12, 5),
                            Nombre = "Michael Brown",
                            Salario = 60000m
                        });
                });

            modelBuilder.Entity("Desafio1MVCGrupoWASP.Models.Empleado", b =>
                {
                    b.HasOne("Desafio1MVCGrupoWASP.Models.Departamento", "Departamento")
                        .WithMany("Empleados")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("Desafio1MVCGrupoWASP.Models.Departamento", b =>
                {
                    b.Navigation("Empleados");
                });
#pragma warning restore 612, 618
        }
    }
}
